//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use super::sea_orm_active_enums::MusicGenre;
use super::sea_orm_active_enums::PublicationStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "lineups")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub ref_airtable: Option<String>,
    pub collective_id: Option<i32>,
    pub music_genres: Option<Vec<MusicGenre>>,
    pub short_title: String,
    pub long_title: String,
    pub catch_phrase: String,
    #[sea_orm(column_type = "Text")]
    pub presentation: String,
    pub status: PublicationStatus,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::collectives::Entity",
        from = "Column::CollectiveId",
        to = "super::collectives::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Collectives,
    #[sea_orm(has_many = "super::events_lineups::Entity")]
    EventsLineups,
    #[sea_orm(has_many = "super::lineups_subscribers::Entity")]
    LineupsSubscribers,
}

impl Related<super::collectives::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Collectives.def()
    }
}

impl Related<super::events_lineups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventsLineups.def()
    }
}

impl Related<super::lineups_subscribers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LineupsSubscribers.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        super::events_lineups::Relation::Events.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::events_lineups::Relation::Lineups.def().rev())
    }
}

impl Related<super::members::Entity> for Entity {
    fn to() -> RelationDef {
        super::lineups_subscribers::Relation::Members.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::lineups_subscribers::Relation::Lineups.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
