//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod bots;
pub mod collectives;
pub mod collectives_referents;
pub mod collectives_subscribers;
pub mod encounters;
pub mod encounters_absents;
pub mod encounters_participants;
pub mod events;
pub mod events_lineups;
pub mod events_volunteers;
pub mod lineups;
pub mod lineups_subscribers;
pub mod locations;
pub mod members;
pub mod sea_orm_active_enums;
pub mod volunteers;
pub mod display;
