//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::bots::Entity as Bots;
pub use super::collectives::Entity as Collectives;
pub use super::collectives_referents::Entity as CollectivesReferents;
pub use super::collectives_subscribers::Entity as CollectivesSubscribers;
pub use super::encounters::Entity as Encounters;
pub use super::encounters_absents::Entity as EncountersAbsents;
pub use super::encounters_participants::Entity as EncountersParticipants;
pub use super::events::Entity as Events;
pub use super::events_lineups::Entity as EventsLineups;
pub use super::events_volunteers::Entity as EventsVolunteers;
pub use super::lineups::Entity as Lineups;
pub use super::lineups_subscribers::Entity as LineupsSubscribers;
pub use super::locations::Entity as Locations;
pub use super::members::Entity as Members;
pub use super::volunteers::Entity as Volunteers;
