services:
  db:
    image: postgres_fr
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      LC_ALL: fr_FR.UTF-8
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - 5432:5432
 
volumes:
  pgdata:
